services:
  laravel:
    build:
      context: ./
      args:
        user: laravel_host
        uid: 1000
    ports:
      - 80:80
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=uniuser
      - MYSQL_PASSWORD=unipass
      - MYSQL_DATABASE=unibase
      - MYSQL_ROOT_PASSWORD=unicloudrootpassword
    volumes:
    - db-data:/var/lib/mysql
    - "./SQL_Scripts/InitialConfiguration.sql:/docker-entrypoint-initdb.d/1.sql"
    - "./SQL_Scripts/newsInsertion.sql:/docker-entrypoint-initdb.d/2.sql"
    - "./SQL_Scripts/dataInsertion.sql:/docker-entrypoint-initdb.d/3.sql"


volumes:
  db-data:
