/*--IMPORTANT--IMPORTANT--IMPORTANT--IMPORTANT--IMPORTANT--IMPORTANT--IMPORTANT--IMPORTANT--IMPORTANT
--CORRER PRIMEIRO O FICHEIRO InitialConfiguration.sql
  3 Anual
  4 Semestral (aka ambos os semestres)
*/
insert into cursos(nome, faculdade, sigla) values('Licenciatura em Geologia', 'Ciencias e tecnologias', 'LGEOL');
insert into cursos(nome, faculdade, sigla) values('Licenciatura em Física', 'Ciencias e tecnologias', 'LF');
insert into cursos(nome, faculdade, sigla) values('Licenciatura em Antropologia', 'Ciencias e tecnologias', 'LA');
insert into cursos(nome, faculdade, sigla) values('Licenciatura em Engenharia e Gestão Industrial', 'Ciencias e tecnologias', 'LEGI');
insert into cursos(nome, faculdade, sigla) values('Licenciatura em Matemática', 'Ciencias e tecnologias', 'LM');
insert into cursos(nome, faculdade, sigla) values('Mestrado Integrado em Arquitetura', 'Ciencias e tecnologias', 'MIA');
insert into cursos(nome, faculdade, sigla) values('Mestrado Integrado em Engenharia Civíl', 'Ciencias e tecnologias', 'MIEC');
insert into cursos(nome, faculdade, sigla) values('Mestrado Integrado em Engenharia do Ambiente', 'Ciencias e tecnologias', 'MIEA');
insert into cursos(nome, faculdade, sigla) values('Mestrado Integrado em Engenharia Electrotécnica e de Computadores', 'Ciencias e tecnologias', 'MIEEC');
insert into cursos(nome, faculdade, sigla) values('Mestrado Integrado em Engenharia Mecânica', 'Ciencias e tecnologias', 'MIEM');
insert into cursos(nome, faculdade, sigla) values('Mestrado Integrado em Engenharia Química', 'Ciencias e tecnologias', 'MIEQ');
insert into cursos(nome, faculdade, sigla) values('Mestrado Integrado em Engenharia Física', 'Ciencias e tecnologias', 'MIEF');
insert into cursos(nome, faculdade, sigla) values('Mestrado Integrado em Engenharia Biomédica', 'Ciencias e tecnologias', 'MIEBIOM');
insert into cursos(nome, faculdade, sigla) values('Licenciatura em Engenharia Informática', 'Ciencias e tecnologias', 'LEI');
insert into cursos(nome, faculdade, sigla) values('Licenciatura em Biologia', 'Ciencias e tecnologias', 'LBIOL');
insert into cursos(nome, faculdade, sigla) values('Licenciatura em Design e Multimedia', 'Ciencias e tecnologias', 'LDM');
insert into cursos(nome, faculdade, sigla) values('Licenciatura em Engenharia e Ciência de Dados', 'Ciencias e tecnologias', 'LECD');
insert into cursos(nome, faculdade, sigla) values('Licenciatura em Química', 'Ciencias e tecnologias', 'LQ');
insert into cursos(nome, faculdade, sigla) values('Licenciatura em Bioquímica', 'Ciencias e tecnologias', 'LBIOQ');
insert into cursos(nome, faculdade, sigla) values('Licenciatura em Química Medicinal', 'Ciencias e tecnologias', 'LQM');
/*Geologia*/
insert into cadeiras(nome, cursoID, ano, semestre) values('Geologia Geral', 1, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Matemáticas Gerais I', 1, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mineralogia', 1, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Petrologia Sedimentar', 1, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química Geral I', 1, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Cartografia Geológica I', 1, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Paleontologia', 1, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Petrologia Ígnea', 1, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Biologia II', 1, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Biologia da Conservação', 1, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Diversidade das Plantas', 1, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Ecologia Geral', 1, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Evolução', 1, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Matemáticas Gerais II', 1, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Microbiologia', 1, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química Geral II', 1, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física Geral I', 1, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Geomatemática', 1, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Geomorfologia', 1, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Petrologia Metamórfica', 1, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sedimentologia', 1, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Estratigrafia', 1, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Geologia Estrutural', 1, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Cartografia Geológica II', 1, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Fisiologia e Toxicologia Ambientais', 1, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física Geral II', 1, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Limnologia', 1, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Palinologia', 1, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Recursos Minerais não Metálicos', 1, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Geofísica', 1, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Geoquímica', 1, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Tectónica', 1, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Geologia de Engenharia', 1, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Recursos Minerais Metálicos', 1, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Geologia Ambiental e Riscos Naturais', 1, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Geologia de Portugal', 1, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Hidrogeologia', 1, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Estágio/Relatório', 1, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Prospecção Geofísica', 1, 3, 2);
/*Física*/
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática I', 2, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física Geral I', 2, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química Geral I', 2, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Técnicas Laboratoriais de Física', 2, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Álgebra Linear e Geometria Analítica', 2, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática II', 2, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Fundamentos da Física Moderna', 2, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física Geral II', 2, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física Laboratorial I', 2, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química Geral II', 2, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Técnicas Laboratoriais de Química', 2, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática III', 2, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Computadores e Programação', 2, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Eletromagnetismo I', 2, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecânica Clássica I', 2, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Termodinâmica', 2, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Eletrónica', 2, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física Laboratorial II', 2, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecânica Clássica II', 2, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecânica Quântica I', 2, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Ondas e Óptica', 2, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física Atómica e Molecular', 2, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física Estatística', 2, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Eletromagnetismo II', 2, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Elementos da Biofísica', 2, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física da Música', 2, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Introdução à Astrofísica', 2, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Laboratórios de Química I', 2, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Métodos Matemáticos da Física', 2, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas Dinâmicos e Complexos', 2, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física Computacional', 2, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física Nuclear e de Partículas', 2, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física da Matéria Condensada', 2, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecânica Quântica II', 2, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Comunicação Científica e Técnica', 2, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('História da Física', 2, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Introdução à Fisica da Música', 2, 3, 2);
/*Antropologia*/
insert into cadeiras(nome, cursoID, ano, semestre) values('Fundamentos da Evolução e Genética', 3, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Introdução à Antropologia Básica', 3, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Primatologia', 3, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Teoria Social e Moderna', 3, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Teoria e História da Antropologia I', 3, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Antropologia da Religião', 3, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Dinâmica das Populações Humanas', 3, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Fundamentos de Estatística Aplicada', 3, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Paleoantropologia', 3, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Teoria e História da Antropologia II', 3, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Antropologia Visual', 3, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Antropologia do Corpo', 3, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Biologia do Comportamento', 3, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Cultura Material e Museologia', 3, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Introdução à Antropologia Médica', 3, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Leituras Avançadas em Antropologia', 3, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Antropologia Evolutiva', 3, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Antropologia da Performance', 3, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Cultura e Cognição', 3, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Ecologia Humana e Adaptação', 3, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Espaço, Cultura e Globalização', 3, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Etnografia e Trabalho de Campo', 3, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Genética Evolutiva das Populações Humanas', 3, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Antropologia e Arquitectura', 3, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Evolução Social', 3, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Introdução à Antropologia Forense', 3, 3, 2);
/*Engenharia e Gestão Industrial*/
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática I', 4, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Desenho Técnico', 4, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física Geral', 4, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Introdução aos Materiais', 4, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Álgebra Linear e Geometria Analítica', 4, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática II', 4, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Eletromagnetismo e Eletricidade', 4, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Introdução à Gestão', 4, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Materiais para Engenharia', 4, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Programação', 4, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática III', 4, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecânica dos Sólidos e Estruturas', 4, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Processos de Fabrico I', 4, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Termodinâmica Aplicada', 4, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Tratamento Estatístico de Dados', 4, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Automação e Controlo Industrial', 4, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Economia de Empresa', 4, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Estatística Aplicada à Engenharia', 4, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Métodos Numéricos e Computacionais', 4, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Processos de Fabrico II', 4, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Elementos de Máquinas', 4, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Fundamentos de Investigação Operacional', 4, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Gestão Financeira', 4, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Gestão de Operações', 4, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecânica de Fluidos', 4, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Eletrotecnia e Máquinas Elétricas', 4, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Gestão da Qualidade', 4, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Logística', 4, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projeto e Produção Assistidos por Computador', 4, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Trasmissão de Calor', 4, 3, 2);
/*Matemática*/
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Infinitesimal I', 5, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Geometria', 5, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Teoria dos Números', 5, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Álgebra Linear e Geometria Analítica I', 5, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Infinitesimal II', 5, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Matemática Discreta', 5, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Métodos de Programação I', 5, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Álgebra Linear e Geometria Analítica II', 5, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Infinitesimal III', 5, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Equações Diferenciais e Modelação', 5, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Grupos e Simetrias', 5, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Métodos de Programação', 5, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Infinitesimal IV', 5, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Corpos e Equações Algébricas', 5, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Curvas e Superfícies', 5, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Probablidades', 5, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física', 5, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física Moderna', 5, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecânica Quântica', 5, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Estatística', 5, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Matemática Numérica I', 5, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Bases de Dados', 5, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Lógica', 5, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Topologia E Análise Linear', 5, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Complexa', 5, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Estatística Computacional', 5, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Matemática Numérica II', 5, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Seminário Matemático', 5, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecânica Celeste', 5, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Programação Linear', 5, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Programação Orientada para os Objectos', 5, 3, 2);
/*Arquitetura*/
insert into cadeiras(nome, cursoID, ano, semestre) values('Construção I', 6, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Introdução à Arquitetura e à Cidade I', 6, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Construção II', 6, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Introdução à Arquitetura e à Cidade II', 6, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Desenho I', 6, 1, 3);
insert into cadeiras(nome, cursoID, ano, semestre) values('Geometria', 6, 1, 3);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projeto I', 6, 1, 3);
insert into cadeiras(nome, cursoID, ano, semestre) values('Construção III', 6, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Desenho II', 6, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('História da Arquitetura I', 6, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Teoria da Arquitetura I', 6, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Arquitetura e Projeto Digital I', 6, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Construção IV', 6, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('História da Arquitetura II', 6, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Teoria da Arquitetura II', 6, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projeto II', 6, 2, 3);
insert into cadeiras(nome, cursoID, ano, semestre) values('Arquitetura e Projeto Digital II', 6, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Construção V', 6, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('História da Arquitetura III', 6, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Teoria da Arquitetura III', 6, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Construção VI', 6, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Desenho III', 6, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('História da Arquitetura IV', 6, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Urbanismo', 6, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projeto III', 6, 3, 3);
insert into cadeiras(nome, cursoID, ano, semestre) values('História da Arquitetura Portuguesa I', 6, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Urbanística', 6, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Arqueologia da Paisagem, Cidade e Território', 6, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Concepção Construtiva e Ambiental', 6, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Do projeto à obra - do licenciamento camarário à preparação da execução da obra', 6, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Fotografia e Composição', 6, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Outras paisagens: habitação e espaço urbano hoje', 6, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas estruturais em edíficios', 6, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Suportes Físicos para Arquitetura e Urbanismo', 6, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('História da Arquitetura Portuguesa II', 6, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Urbanização', 6, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Arquitetura Portuguesa do Século XX', 6, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Estratégias de Reabilitação funcional de edíficios', 6, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Geografia Urbana', 6, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Gestão e Financiamento da Reabilitação', 6, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('História e Estética do Cinema', 6, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Investigação em Arquitetura', 6, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Políticas e Direito da Reabilitação', 6, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Teorias e Práticas de Reconstrução', 6, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Ambiente e Organização do Espaço', 6, 4, 4);
insert into cadeiras(nome, cursoID, ano, semestre) values('Antropologia, Cultura e Arquitetura', 6, 4, 4);
insert into cadeiras(nome, cursoID, ano, semestre) values('Arquiteturas Virtuais', 6, 4, 4);
insert into cadeiras(nome, cursoID, ano, semestre) values('Arquitetónicas da Forma', 6, 4, 4);
insert into cadeiras(nome, cursoID, ano, semestre) values('Conceitos e Práticas da Arte Contemporânea', 6, 4, 4);
insert into cadeiras(nome, cursoID, ano, semestre) values('Construção do Edificado - Condições para a Prática Projetual Construtiva II', 6, 4, 4);
insert into cadeiras(nome, cursoID, ano, semestre) values('Construção do Edificado - Condições para a Prática Projetual Construtiva I', 6, 4, 4);
insert into cadeiras(nome, cursoID, ano, semestre) values('Construção e Tecnologia', 6, 4, 4);
insert into cadeiras(nome, cursoID, ano, semestre) values('Expressão Plástica e Multimédia', 6, 4, 4);
insert into cadeiras(nome, cursoID, ano, semestre) values('Gestão de Energia em Edifícios', 6, 4, 4);
insert into cadeiras(nome, cursoID, ano, semestre) values('Instalações Técnicas em Edifícios', 6, 4, 4);
insert into cadeiras(nome, cursoID, ano, semestre) values('Intervenção no Património Cultural Edificado', 6, 4, 4);
insert into cadeiras(nome, cursoID, ano, semestre) values('Materiais Geológicos e Arquitetura', 6, 4, 4);
insert into cadeiras(nome, cursoID, ano, semestre) values('Organização do Projeto e Prática Profissional', 6, 4, 4);
insert into cadeiras(nome, cursoID, ano, semestre) values('Políticas e Direito de Reabilitação', 6, 4, 4);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projeto Moderno e Arquitetura', 6, 4, 4);
insert into cadeiras(nome, cursoID, ano, semestre) values('Urbanismo Arquitetura e Turismo', 6, 4, 4);
insert into cadeiras(nome, cursoID, ano, semestre) values('Seminário de Investigação', 6, 5, 1);
/*Engenharia Civil*/
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática I', 7, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física Geral I', 7, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Informática', 7, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Introdução à Engenharia Civil', 7, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química Geral', 7, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Álgebra Linear e Geometria Analítica', 7, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática II', 7, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física Geral', 7, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecânica I', 7, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Métodos Estatísticos', 7, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Topografia', 7, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática III', 7, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Competência Transversal I', 7, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Desenho Técnico', 7, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecânica II', 7, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecânica dos Meios Contínuos', 7, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Métodos Numéricos', 7, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Geologia da Engenharia', 7, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Hidráulica Geral I', 7, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Materiais de Construção', 7, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Resistência dos Materiais I', 7, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas de Engenharia', 7, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Hidráulica Geral II', 7, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecânica dos Solos I', 7, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Planeamento Regional e Urbano', 7, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Cartografia e Sistemas de Informação Geográfica', 7, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física das Construções', 7, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Geodesia', 7, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Geologia Estrutural', 7, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecânica das Rochas', 7, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Resistência dos Materiais II', 7, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Betão Armado I', 7, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Cadastro', 7, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Cartografia Geológica', 7, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Fotogrametria', 7, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Hidrologia e Recursos Hídricos', 7, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecânica dos Solos II', 7, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mineralogia e Petrologia', 7, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Prospecção Geofísica', 7, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Teoria das Estruturas I', 7, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Topografia Aplicada', 7, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Vias de Comunicação I', 7, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Betão Armado II', 7, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Saneamento Básico', 7, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Tecnologia das Construções', 7, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Teoria das Estruturas II', 7, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Vias de Comunicação II', 7, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Direcção, Gestão e Fiscalização de Obras', 7, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Estruturas Metálicas', 7, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Fundações', 7, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Gestão de Empreendimentos', 7, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Impactes Ambientais', 7, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projecto Urbano', 7, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Competência Transversal II', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Competência Transversal III', 7, 5, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Dissertação em Construções', 7, 5, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Acústica Aplicada', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Comportamento Térmico e Energético de Edifícios', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Construção Sustentável', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Instalações e Sistemas Técnicos em Edifícios', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Reabilitação Não-Estrutural', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Segurança e Processos Gerais de Construção', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sustentabilidade do Ambiente Construído', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Dissertação em Estruturas', 7, 5, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Conceção e Dimensionamento de Estruturas', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Conservação e Reabilitação de Estruturas', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Estruturas de Betão', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Estruturas de Madeira e Alvenaria', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projecto Assistido por Computador', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Dissertação em Geotecnia', 7, 5, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Engenharia Sísmica Geotécnica', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecânica dos Solos do Estado Crítico', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Obras de Escavação e Contenção', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Obras de Terra', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Dissertação em Hidráulica, Recursos Hídricos e Ambiente', 7, 5, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Aproveitamentos Energéticos', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Engenharia Fluvial e Costeira', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Gestão Integrada de Recursos Hídricos', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Instalações e Obras Hidráulicas', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projecto Assistido por Computador em Hidráulica Urbana', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projecto e Exploração de ETAR', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Dissertação em Mecânica Estrutural', 7, 5, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Não Linear de Estruturas', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Dinâmica e Dimensionamento Sísmico', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Estruturas Metálicas II', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Pontes', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projecto de Estrutura e Fundações', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Dissertação em Urbanismo, Transportes e Vias de Comunicação', 7, 5, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Engenharia de Infraestruturas de Transporte', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Engenharia de Tráfego', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Planeamento de Equipamentos Coletivos', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Planeamento de Transportes', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Planeamento e Gestão Urbanística Municipal', 7, 5, 1);
/*Engenharia Do Ambiente*/
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática I', 8, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Desenho Técnico', 8, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física Geral I', 8, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Informática', 8, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Introdução à Engenharia do Ambiente', 8, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química Geral', 8, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática II', 8, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Cartografia e Sistemas de Informação Geográfica', 8, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física Geral II', 8, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Geologia Geral', 8, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Álgebra Linear e Geometria Analítica', 8, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática III', 8, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Biologia', 8, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Métodos Numéricos', 8, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química Orgânica', 8, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química-Física', 8, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Microbiologia', 8, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Métodos Estatísticos', 8, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Métodos Instrumentais de Análise', 8, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas de Engenharia', 8, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Termodinâmica', 8, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Ecologia Geral', 8, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecânica dos Fluidos', 8, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecânica dos Solos', 8, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mudanças Globais e Climatologia', 8, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Planeamento Regional e Urbano', 8, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Acústica Ambiental', 8, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise de Riscos', 8, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Ecologia Aplicada', 8, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Fenómenos de Transferência', 8, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Hidrologia e Recursos Hídricos', 8, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Competência Transversal I', 8, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Economia Ambiental', 8, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Efluentes Gasosos e Qualidade do Ar', 8, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Gestão Ambiental', 8, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas de Abastecimento e Drenagem de Água', 8, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Tratamentos Físico-Químicos', 8, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Geotecnia Ambiental', 8, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Gestão e Tratamento de Resíduos', 8, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Impactes Ambientais', 8, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas Energéticos', 8, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Tratamentos Biológicos', 8, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Dissertação de Mestrado em Tecnologia e Gestão do Ambiente', 8, 5, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Competência Transversal II', 8, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Ecologia Industrial', 8, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Energética do Meio Ambiente', 8, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Gestão de Energia', 8, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Higiene e Segurança', 8, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Materiais e Reciclagem', 8, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Competência Transversal III', 8, 5, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Dissertação (Território e Gestão do Ambiente)', 8, 5, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Gestão da Água', 8, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Gestão de Energia em Edifícios', 8, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Políticas e Desenvolvimento Sustentável', 8, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas Fluviais Costeiros', 8, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Transportes e Ambiente', 8, 5, 1);
/*Engenharia Eletrotécnica e de Computadores*/
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática I', 9, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Laboratório de Sistemas Digitais', 9, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Programação de Computadores', 9, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Álgebra Linear e Geometria Analítica', 9, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática II', 9, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Competências Transversais para a Engenharia', 9, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Laboratório de Circuitos e Simulação', 9, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecânica e Ondas', 9, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas de Microprocessadores', 9, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática III', 9, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Circuitos Eléctricos', 9, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Materiais Elétricos e Semicondutores', 9, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projeto I', 9, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sinais e Sistemas', 9, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Electromagnetismo', 9, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Electrónica I', 9, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Estruturas de Dados e Algoritmos', 9, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Probabilidades e Estatística', 9, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Processamento de Sinal', 9, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Bases de Dados', 9, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Conversão de Energia Elétrica', 9, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Electrónica II', 9, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Ondas e Propagação', 9, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas de Controlo', 9, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projeto II', 9, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Técnicas de Planeamento e Gestão', 9, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Automação Industrial', 9, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Instrumentação e Medidas', 9, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Introdução aos Sistemas de Energia Eléctrica', 9, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Introdução às Comunicações', 9, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Redes de Computadores', 9, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas Embebidos', 9, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas Operativos', 9, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Controlo Digital', 9, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Robótica', 9, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sensores Inteligentes', 9, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas de Tempo Real', 9, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecatrónica', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projecto de Controlo Digital', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas Robóticos Autónomos', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Visão por Computador', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Compatibilidade Electromagnética', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Complementos de Investigação Operacional', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Elementos Finitos Aplicados à Engenharia Eletrotécnica', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Fabricação Digital e Sistemas Micro-Electrónico-Mecânicos', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Gestão Inteligente de Energia em Edifícios', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Microondas', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Processamento Avançado de Vídeo', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Seleção e Manutenção de Motores Elétricos', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas Rádio Definidos por Software', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Controlo Difuso e Aprendizagem', 9, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Empreendedorismo, Inovação e Transferência de Tecnologia', 9, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projeto de Dissertação', 9, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Dissertação', 9, 5, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Aplicações de Accionamentos Eléctricos', 9, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Co-Projecto de Hardware e Software', 9, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Comunicações nas Redes Elétricas Inteligentes', 9, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Controlo Não Destrutivo', 9, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Fundamentos de Investigação Operacional', 9, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mercados e Qualidade de Energia', 9, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Redes de Transporte e Acesso de Próxima Geração', 9, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Redes Ópticas', 9, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Robótica Médica', 9, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas de Controlo de Potência', 9, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas e Robôs Interativos', 9, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Visão Robótica', 9, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Electrónica de Potência', 9, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Redes Elétricas Inteligentes', 9, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Arquitectura de Computadores', 9, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Engenharia de Software', 9, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Processamento Digital de Sinal', 9, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Computação Gráfica e Realidade Aumentada', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Internet das Coisas', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projecto de Sistemas Digitais', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Comunicações Móveis', 9, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Computação Heterogénea de Alto Desempenho', 9, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Produção de Energia Elétrica', 9, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projectos de Instalações Eléctricas', 9, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Regime Estacionário em Sistemas de Energia Elétrica', 9, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Transformadores e Máquinas Assíncronas', 9, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Acionamentos Elétricos', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Gestão de Energia Eléctrica', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Máquinas Síncronas', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Regime Transitório em Sistemas de Energia Elétrica', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Proteções e Fiabilidade em Sistemas de Energia Elétrica', 9, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Antenas', 9, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Electrónica para Telecomunicações', 9, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Fundamentos de Sistemas de Comunicação', 9, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Teoria da Informação e da Codificação', 9, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Engenharia de Redes de Comunicação', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas de Comunicação Digital', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas de Comunicação Ópticos', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Transmissão de Informação Multimédia', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Tecnologias de Redes de Comunicação', 9, 5, 1);
/*Engenharia Mecânica*/
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática I', 10,1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Desenho Técnico I', 10,1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Estrutura e Propriedades dos Materiais', 10,1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Programação de Computadores', 10,1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Álgebra Linear e Geometria Analítica', 10,1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática II', 10,1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Desenho Técnico II', 10,1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física Geral I', 10,1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Métodos Numéricos e Computacionais', 10,1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Probabilidades e Estatística', 10,1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática III', 10,2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Ciência e Engenharia de Materiais I', 10,2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física Geral II', 10,2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecânica Aplicada', 10,2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Termodinâmica', 10,2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Ciência e Engenharia de Materiais II', 10,2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Elasticidade e Plasticidade', 10,2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Instrumentação e Medida', 10,2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Resistência de Materiais I', 10,2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Termodinâmica Aplicada', 10,2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Automação Industrial', 10,3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Comportamento Mecânico de Materiais', 10,3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecânica dos Fluidos I', 10,3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Resistência de Materiais II', 10,3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Tecnologia Mecânica I', 10,3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Gestão da Produção', 10,3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Introdução ao Projecto Mecânico', 10,3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecânica dos Fluidos II', 10,3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecânica dos Sólidos', 10,3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Transmissão de Calor', 10,3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Cálculo Automático de Estruturas', 10,4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Economia e Gestão Industrial', 10,4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Eletrotecnia e Máquinas Elétricas', 10,4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Tecnologia Mecânica II', 10,4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Transferência de Calor e Massa', 10,4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Climatização e Refrigeração', 10,4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Combustão', 10,4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Controlo Industrial', 10,4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Vibrações e Ruído', 10,4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Órgãos de Máquinas', 10,4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projecto de Sistemas Energéticos', 10,5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Dissertação de Mestrado', 10,5, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Aerodinâmica', 10,5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Energética do meio ambiente', 10,5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Gestão Energética e Ambiental', 10,5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Gestão da Qualidade', 10,5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Higiene e Segurança Ocupacionais', 10,5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Inovação e Empreendedorismo', 10,5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Manutenção', 10,5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Modelação Numérica de Fenómenos de Transferência', 10,5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Motores de Combustão Interna', 10,5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Turbomáquinas', 10,5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projecto de Sistemas Mecânicos', 10,5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Investigação Operacional', 10,5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecânica Computacional em Tecnologia', 10,5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Robótica Industrial', 10,5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Selecção de Materiais e Processos de Fabrico', 10,5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Tecnologia Mecânica III', 10,5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Tecnologias Avançadas', 10,5, 1);
/*Mestrado Engenharia Química*/
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática I', 11, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física I', 11, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Introdução à Engenharia Química', 11, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química Geral', 11, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Álgebra Linear e Geometria Analítica', 11, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática II', 11, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física II', 11, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Introdução aos Processos Biológicos', 11, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química Analítica', 11, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química Orgânica', 11, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática III', 11, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Balanços Mássicos e Energéticos', 11, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Computação Aplicada', 11, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Fenómenos de Transferência I', 11, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Termodinâmica Química', 11, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Fenómenos de Transferência II', 11, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Introdução aos Materiais e Caracterização', 11, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Laboratórios de Engenharia Química I', 11, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Modelação, Simulação e Otimização', 11, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química-Física de Superfícies', 11, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Estatística Aplicada', 11, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Fenómenos de Transferência III', 11, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Instrumentação e Técnicas Analíticas', 11, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Processos de Separação I', 11, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Reatores Químicos I', 11, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Gestão e Empreendedorismo', 11, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Instalações e Equipamentos Industriais', 11, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Laboratórios de Engenharia Química II', 11, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Processos de Separação II', 11, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Reatores Químicos II', 11, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Ciência de Polímeros', 11, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Efluentes e Resíduos Industriais', 11, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Engenharia Bioquímica', 11, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Engenharia Química de Base Molecular', 11, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Biomateriais', 11, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Introdução ao Projeto de Processo', 11, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projeto de Produto', 11, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Supervisão de Processos', 11, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Biossensores e Sinais Biomédicos', 11, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Ciência e Tecnologia do Papel', 11, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Eletroquímica e Corrosão', 11, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Engenharia de Tecidos', 11, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Engenharia e Sistemas da Qualidade', 11, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Gestão da Melhoria de Processos', 11, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Gestão de Projetos e Operações', 11, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Tecnologias de Sistemas Dispersos', 11, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Técnicas Avançadas de Modelação e Simulação', 11, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Ciência e Tecnologia da Pasta', 11, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Desenvolvimento de Fármacos e Processos Farmacêuticos', 11, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Energia e Biocombustíveis', 11, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Integração e Intensificação de Processos', 11, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Nanotecnologias', 11, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Tecnologias de Controlo da Poluição Industrial', 11, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projeto de Processo', 11, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Segurança de Processos Químicos', 11, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sustentabilidade e Ecologia Industrial', 11, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Dissertação em Engenharia Química', 11, 5, 2);
/*Mestrado em Engenharia Física*/
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática I', 12, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física Geral I', 12, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química Geral', 12, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Seminários de Engenharia Física', 12, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Álgebra Linear e Geometria Analítica', 12, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática II', 12, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Computadores e Programação', 12, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Fundamentos de Física Moderna', 12, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física Geral II', 12, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Laboratórios de Física', 12, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática III', 12, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Electromagnetismo I', 12, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecânica Clássica', 12, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Termodinâmica', 12, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Tratamento Estatístico de Dados', 12, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Electrónica', 12, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecânica Quântica I', 12, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Modelação Computacional', 12, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Ondas e Óptica', 12, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sinais e Sistemas', 12, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física Atómica e Molecular', 12, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Instrumentação e Sistemas de Aquisição de Dados', 12, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecânica dos Fluidos', 12, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Processos de Gestão', 12, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Tecnologia de Sistemas Embebidos', 12, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Comunicação Científica e Técnica', 12, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física Nuclear', 12, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física da Matéria Condensada', 12, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projecto e Concepção de Instrumentos', 12, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas Informáticos', 12, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Complementos de Electrónica', 12, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Inovação e Empreendedorismo Tecnológico', 12, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Instrumentação Optoelectrónica', 12, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Técnicas de Planeamento e Gestão', 12, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise e Processamento de Imagem', 12, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física e Tecnologia do Vácuo e da Criogenia', 12, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Instrumentação para Imagiologia Médica', 12, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Interacção da Radiação com a Matéria', 12, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Semicondutores e Nanoestruturas', 12, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sensores Inteligentes', 12, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Tecnologias Quânticas', 12, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Compatibilidade Electromagnética', 12, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Gestão da Qualidade', 12, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Instrumentação Industrial', 12, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Instrumentação Médica e Hospitalar', 12, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecatrónica', 12, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Qualidade, Ambiente, Segurança e Licenciamento Industrial', 12, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Simulação e Métodos de Monte Carlo', 12, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Telemetria e Telegestão', 12, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Instrumentação para Física da Radiação', 12, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Seminários de Instrumentação', 12, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projecto', 12, 5, 3);
insert into cadeiras(nome, cursoID, ano, semestre) values('Metrologia', 12, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Dosimetria da Radiação e Radioprotecção', 12, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Propriedades Físicas dos Materiais', 12, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Técnicas de Análise de Materiais', 12, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Métodos Instrumentais Avançados de Análise', 12, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Seminários de Metrologia', 12, 5, 1);
/*Engenharia Biomédica*/
insert into cadeiras(nome, cursoID, ano, semestre) values('Algoritmos de Diagnóstico e de Auto-Regulação', 13, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Anatomia e Histologia', 13, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise e Processamento de BioSinais', 13, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise e Processamento de Imagem', 13, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática I', 13, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática II', 13, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática III', 13, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Aprendizagem Computacional', 13, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Bases de Dados e Análise de Informação', 13, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Biocompatibilidade', 13, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Bioelectricidade e Biomagnetismo', 13, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Bioestatística', 13, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Biologia Celular do Desenvolvimento Humano', 13, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Biologia Celular e Molecular', 13, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Biologia do Envelhecimento', 13, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Biomateriais', 13, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Biomecânica', 13, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Bioquímica', 13, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Biosensores e Sinais Biomédicos', 13, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Co-Projecto de Hardware e Software', 13, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Complementos de Investigação Operacional', 13, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Computadores e Programação', 13, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Computação Evolucionária', 13, 4, 4);
insert into cadeiras(nome, cursoID, ano, semestre) values('Computação Gráfica e Realidade Aumentada', 13, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Computação Móvel', 13, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Computação Neuronal e Sistemas Difusos', 13, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Dosimetria da Radiação e Radiobiologia', 13, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Dosimetria, Segurança e Protecção Radiológica', 13, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Electrónica', 13, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Engenharia de Tecidos', 13, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Fabricação Digital e Sistemas Micro-Electrónico-Mecânicos', 13, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Fundamentos de Fisiologia I', 13, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Fundamentos de Fisiologia II', 13, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Fundamentos de Imagem para Diagnóstico e Terapêutica', 13, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Fundamentos de Investigação Operacional', 13, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física Biológica', 13, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física I', 13, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física II', 13, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física Quântica', 13, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Informática Clínica e Sistemas de Tele-Saúde', 13, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Inovação e Empreendedorismo Tecnológico', 13, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Instrumentação Médica e Hospitalar', 13, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Instrumentação Optoelectrónica', 13, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Instrumentação para Imagiologia Médica', 13, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Integração de Sistemas', 13, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Inteligência Artificial', 13, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Inteligência no Negócio', 13, 4, 4);
insert into cadeiras(nome, cursoID, ano, semestre) values('Interacção Humano-Computador', 13, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Interfaces e Sistemas de Aquisição de Dados', 13, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Introdução à Bioinformática', 13, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Introdução à Química Nuclear e Radiofarmácia', 13, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Materiais para Bioengenharia', 13, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecatrónica I', 13, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecatrónica II', 13, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Medicina Regenerativa', 13, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Membranas e Comunicação Celular', 13, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Modelos Computacionais de Processos Fisiológicos', 13, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Métodos Computacionais para Biomedicina', 13, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Nanobiomateriais', 13, 4, 4);
insert into cadeiras(nome, cursoID, ano, semestre) values('Neurobiologia I', 13, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Neurobiologia II', 13, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Neurofarmacologia', 13, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Ondas e Óptica', 13, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Processamento de Materiais', 13, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Processos de Gestão', 13, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Processos de Transferência e Transporte', 13, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projecto', 13, 5, 3);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projeto e Conceção de Instrumentos', 13, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química Geral', 13, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Radiações em Biomedicina', 13, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Reconhecimento de Padrões', 13, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Revestimento de Superfícies', 13, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Robótica Médica', 13, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Segurança em Tecnologias da Informação', 13, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sensores Inteligentes', 13, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas Baseados em Conhecimento', 13, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas Complexos', 13, 4, 4);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas e Robôs Interativos', 13, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas Informáticos', 13, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas Ubíquos', 13, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Tecnologias da Internet', 13, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Tecnologias de Investigação em Neurobiologia', 13, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Técnicas Avançadas de Caracterização de Materiais', 13, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Técnicas de Análise de Materiais', 13, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Técnicas de Planeamento e Gestão', 13, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Técnicas Laboratoriais de Física', 13, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Visualização de InformaçãoI', 13, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Visualização de InformaçãoII', 13, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Visão computacional e Percepção Biológica', 13, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Visão por Computador', 13, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Álgebra Linear e Geometria Analítica', 13, 1, 2);
/*Engenharia Informática*/
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática I', 14, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Estruturas Discretas', 14, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Introdução à Programação e Resolução de Problemas', 14, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Tecnologia da Informática', 14, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Álgebra Linear e Geometria Analítica', 14, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática II', 14, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Comunicação Técnica', 14, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Estatística', 14, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Princípios de Programação Procedimental', 14, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Tópicos de Física Moderna', 14, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática III', 14, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Arquitetura de Computadores', 14, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Programação Orientada aos Objetos', 14, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Teoria da Computação', 14, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Teoria da Informação', 14, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Algoritmos e Estruturas de Dados', 14, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise e Transformação de Dados', 14, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Bases de Dados', 14, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Redes de Comunicação', 14, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas Operativos', 14, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Compiladores', 14, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Computação Gráfica', 14, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Engenharia de Software', 14, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Processos de Gestão e de Inovação', 14, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas de Informação', 14, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Estratégias Algorítmicas', 14, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Fundamentos de Inteligência Artificial', 14, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Multimédia', 14, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Protocolos de Comunicação', 14, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas Distribuídos', 14, 3, 2);
/*Biologia*/
insert into cadeiras(nome, cursoID, ano, semestre) values('Algas e Fungos', 15, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Aquacultura e Pescas', 15, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Bioestatística', 15, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Bioinformática', 15, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Biologia Celular', 15, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Biologia da Conservação', 15, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Biologia do Comportamento', 15, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Biologia e Ecologia Marinha', 15, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Biologia Molecular', 15, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Biologia Translacional e Biomedicina', 15, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Bioquímica', 15, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Biotecnologia Vegetal', 15, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Desafios Societais - Ambiente', 15, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Desafios Societais - Saúde', 15, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Desenvolvimento das Plantas', 15, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Diferenciação e Desenvolvimento', 15, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Diversidade Animal', 15, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Diversidade das Plantas', 15, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Ecofisiologia', 15, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Ecologia das Populações e Comunidades', 15, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Ecologia Funcional', 15, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Evolução', 15, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Fisiologia Animal', 15, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Fisiologia Celular', 15, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Fisiologia Humana', 15, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Fisiologia Vegetal', 15, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física', 15, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Genética', 15, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Indicadores Ecológicos', 15, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Matemática', 15, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Metabolismo', 15, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Microbiologia', 15, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Métodos e Técnicas em Biologia Molecular', 15, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Métodos e Técnicas em Citologia e Fisiologia', 15, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Primatologia', 15, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projeto em Biologia Aplicada I', 15, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projeto em Biologia Aplicada II', 15, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química', 15, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Zoologia', 15, 1, 1);
/*Desing e Multimédia*/
insert into cadeiras(nome, cursoID, ano, semestre) values('Desenho e Representação', 16, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Fundamentos Matemáticos', 16, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('História do Design', 16, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Introdução à Programação e Resolução de Problemas', 16, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Desenho e Composição', 16, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Programação Multimédia', 16, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Teoria do Design e Comunicação', 16, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Tipografia', 16, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Arte e Cultura Moderna', 16, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projeto 1 - Identidade na Web', 16, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Tecnologias da Internet', 16, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Tipografia em Meios Digitais', 16, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Comunicação Multimédia', 16, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Fotografia e Composição', 16, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Produção Audiovisual', 16, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projeto 2 - Audiovisual', 16, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Arte e Cultura Contemporânea', 16, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Engenharia de Software', 16, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projeto 3 - Aplicações Multimédia', 16, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas Informáticos', 16, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Computação Gráfica', 16, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Design de Meios Interativos', 16, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Introdução à Inteligência Artificial', 16, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projeto 4 - Multimédia Interativo', 16, 3, 2);
/*Ciência d Dados*/
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática I', 17, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física', 17, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Introdução à Programação e Resolução de Problemas', 17, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Otimização e Análise em Grafos', 17, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Álgebra Linear e Geometria Analítica', 17, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática II', 17, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Estatística', 17, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Introdução à Engenharia e Ciência de Dados', 17, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Programação Orientada aos Objetos', 17, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Álgebra Linear Numérica e Cálculo Científico', 17, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Algoritmos e Estruturas de Dados', 17, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Estatística para Ciência de Dados', 17, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Otimização Contínua', 17, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas de Gestão de Dados', 17, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Tópicos de Inteligência Artificial', 17, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise e Transformação de Dados', 17, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Aprendizagem Computacional', 17, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Processos de Gestão e de Inovação', 17, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas Distribuídos', 17, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas e Redes de Sensorização e Atuação', 17, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Dados Sociedade e Direito', 17, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Engenharia de Atributos', 17, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Processamento de Linguagem Natural', 17, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas e Infraestrututuras de Computação', 17, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Visualização de Dados', 17, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Aprendizagem Probabilística e Reconhecimento de Padrões', 17, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Processamento Audiovisual', 17, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projeto de Engenharia e Ciência de Dados', 17, 3, 2);
/*Química*/
insert into cadeiras(nome, cursoID, ano, semestre) values('Física Geral I', 18, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Matemática I', 18, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química Geral I', 18, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Tutorial em Química', 18, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Técnicas Laboratoriais de Química', 18, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física Geral II', 18, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física Laboratorial I', 18, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Informática Geral', 18, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Matemática II', 18, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química Geral II', 18, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química e Sociedade', 18, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Laboratórios de Química I', 18, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química Física I', 18, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química Inorgânica', 18, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química Orgânica I', 18, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química Teórica e Estrutural', 18, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Laboratórios de Química II', 18, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química Analítica I', 18, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química Física II', 18, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química Orgânica II', 18, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química dos Materiais', 18, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Laboratórios de Química III', 18, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química Analítica II', 18, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química Biológica', 18, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química de Organometálicos e Catálise', 18, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Bioquímica', 18, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Estágio Laboratorial', 18, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química Computacional', 18, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Síntese Química', 18, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Dinâmica de Fluidos', 18, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Tratamento de Águas e Efluentes', 18, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Bioelectroquímica', 18, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Controlo Químico da Qualidade', 18, 3, 2);
/*BioQuímica*/
insert into cadeiras(nome, cursoID, ano, semestre) values('Física Geral', 19, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Introdução ao Laboratório de Bioquímica', 19, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Introdução à Biologia', 19, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Matemática e Modelação', 19, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química Geral', 19, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Bioquímica Física', 19, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Fundamentos de Fisiologia', 19, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Laboratórios de Bioquímica Analítica', 19, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Métodos Estatísticos', 19, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química Orgânica', 19, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Bioquímica Inorgânica', 19, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Bioquímica de Proteínas, Ácidos Nucleico e Lipídos', 19, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Fundamentos de Biologia Molecular', 19, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Introdução à Bioinformática', 19, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Laboratórios de Microbiologia', 19, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Microbiologia Geral', 19, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Bioquímica do Metabolismo', 19, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Espectroscopia Biomolecular', 19, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Introdução à Bioquímica Estrutural', 19, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Laboratórios de Biologia Molecular', 19, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Laboratórios de Bioquímica Inorgânica', 19, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Biofísica Celular', 19, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Laboratórios de Enzimologia e Química de Proteínas', 19, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Laboratórios de Fisiologia e Biofísica Celular', 19, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projecto', 19, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Bioestatística', 19, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Bioinformática', 19, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Biotecnologia Vegetal', 19, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Desenvolvimento de Fármacos I', 19, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Ecologia das Populações e Comunidades', 19, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Electromagnetismo I', 19, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Fisiologia Humana', 19, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Genética', 19, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Instrumentação e Sistemas de Aquisição de Dados', 19, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Metais em Medicina e no Ambiente', 19, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Processos de Transferência e Transporte', 19, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química Analítica II', 19, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química Teórica e Estrutural', 19, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química de Organometálicos e Catálise', 19, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Radiações em Biomedicina', 19, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Termodinâmica', 19, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Toxicologia Bioquímica e Biofísica', 19, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Tratamento de Águas e Efluentes', 19, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise e Processamento de BioSinais', 19, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Bioelectricidade e Biomagnetismo', 19, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Bioelectroquímica', 19, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Biomateriais', 19, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Biomecânica', 19, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Computadores e Programação', 19, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Comunicação Científica e Técnica', 19, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Controlo Químico da Qualidade', 19, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Desenvolvimento das Plantas', 19, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Diferenciação e Desenvolvimento', 19, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Elementos de Quimioinformática', 19, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Fisiologia Vegetal', 19, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Infecção e Imunidade', 19, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Instrumentação Médica e Hospitalar', 19, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Laboratórios de Química II', 19, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Nutrição e Metabolismo', 19, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Ondas e Óptica', 19, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Palinologia', 19, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Programação Orientada para os Objectos', 19, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química Computacional', 19, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química Orgânica II', 19, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química dos Materiais', 19, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química e Sociedade', 19, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Síntese Química', 19, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Síntese de Bioconjugados', 19, 3, 2);
/*Quimica Medicinal*/
