/*--IMPORTANT--IMPORTANT--IMPORTANT--IMPORTANT--IMPORTANT--IMPORTANT--IMPORTANT--IMPORTANT--IMPORTANT
--CORRER PRIMEIRO O FICHEIRO InitialConfiguration.sql
  3 Anual
  4 Semestral (aka ambos os semestres)
*/
insert into cursos(nome, faculdade) values('Licenciatura em Geologia', 'Ciencias e tecnologias');
insert into cursos(nome, faculdade) values('Licenciatura em Fisica', 'Ciencias e tecnologias');
insert into cursos(nome, faculdade) values('Licenciatura em Antropologia', 'Ciencias e tecnologias');
insert into cursos(nome, faculdade) values('Licenciatura em Engenharia e Gestão Industrial', 'Ciencias e tecnologias');
insert into cursos(nome, faculdade) values('Licenciatura em Matemática', 'Ciencias e tecnologias');
insert into cursos(nome, faculdade) values('Mestrado Integrado em Arquitetura', 'Ciencias e tecnologias');
insert into cursos(nome, faculdade) values('Mestrado Integrado em Engenharia Civil', 'Ciencias e tecnologias');
insert into cursos(nome, faculdade) values('Mestrado Integrado em Engenharia do Ambiente', 'Ciencias e tecnologias');
insert into cursos(nome, faculdade) values('Mestrado Integrado em Engenharia Electrotécnica e de Computadores', 'Ciencias e tecnologias');
insert into cursos(nome, faculdade) values('Mestrado Integrado em Engenharia Mecânica', 'Ciencias e tecnologias');
insert into cursos(nome, faculdade) values('Mestrado Integrado em Engenharia Química', 'Ciencias e tecnologias');
insert into cursos(nome, faculdade) values('Mestrado Integrado em Engenharia Física', 'Ciencias e tecnologias');
insert into cursos(nome, faculdade) values('Mestrado Integrado em Engenharia Biomédica', 'Ciencias e tecnologias');
insert into cursos(nome, faculdade) values('Licenciatura em Engenharia Informatica', 'Ciencias e tecnologias');
insert into cursos(nome, faculdade) values('Licenciatura em Biologia', 'Ciencias e tecnologias');
insert into cursos(nome, faculdade) values('Licenciatura em Design e Multimedia', 'Ciencias e tecnologias');
insert into cursos(nome, faculdade) values('Licenciatura em Engenharia e Ciencia de Dados', 'Ciencias e tecnologias');
insert into cursos(nome, faculdade) values('Licenciatura em Química', 'Ciencias e tecnologias');
insert into cursos(nome, faculdade) values('Licenciatura em Bioquímica', 'Ciencias e tecnologias');
/*Geologia*/
insert into cadeiras(nome, cursoID, ano, semestre) values('Geologia Geral', 1, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Matemáticas Gerais I', 1, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mineralogia', 1, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Petrologia Sedimentar', 1, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química Geral I', 1, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Cartografia Geológica I', 1, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Paleontologia', 1, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Petrologia Ígnea', 1, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Biologia II', 1, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Biologia da Conservação', 1, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Diversidade das Plantas', 1, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Ecologia Geral', 1, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Evolução', 1, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Matemáticas Gerais II', 1, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Microbiologia', 1, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química Geral II', 1, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Fisica Geral I', 1, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Geomatemática', 1, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Geomorfologia', 1, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Petrologia Metamórfica', 1, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sedimentologia', 1, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Estratigrafia', 1, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Geologia Estrutural', 1, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Cartografia Geológica II', 1, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Fisiologia e Toxicologia Ambientais', 1, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física Geral II', 1, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Limnologia', 1, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Palinologia', 1, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Recursos Minerais não Metálicos', 1, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Geofísica', 1, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Geoquímica', 1, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Tectónica', 1, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Geologia de Engenharia', 1, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Recursos Minerais Metálicos', 1, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Geologia Ambiental e Riscos Naturais', 1, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Geologia de Portugal', 1, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Hidrogeologia', 1, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Estágio/Relatório', 1, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Prospecção Geológica', 1, 3, 2);
/*Física*/
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática I', 2, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física Geral I', 2, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química Geral I', 2, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Técnicas Laboratoriais de Física', 2, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Álgebra Linear e Geometria Analítica', 2, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática II', 2, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Fundamentos da Fisica Moderna', 2, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física Geral II', 2, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física Laboratorial I', 2, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química Geral II', 2, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Técnicas Laboratoriais de Química', 2, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática III', 2, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Computadores e Programação', 2, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Eletromagnetismo I', 2, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecânica Clássica I', 2, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Termodinâmica', 2, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Eletrónica', 2, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física Laboratorial II', 2, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecânica Clássica II', 2, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecânica Quântica I', 2, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Ondas e Óptica', 2, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física Atómica e Molecular', 2, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física Estatística', 2, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Eletromagnetismo II', 2, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Elementos da Biofísica', 2, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física da Música', 2, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Introdução à Astrofísica', 2, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Laboratórios de Química I', 2, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Métodos Matemáticos da Física', 2, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas Dinâmicos e Complexos', 2, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física Computacional', 2, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física Nuclear e de Partículas', 2, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física da Matéria Condensada', 2, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecânica Quântica II', 2, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Comunicação Científica e Técnica', 2, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('História da Física', 2, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Introdução à Fisica da Música', 2, 3, 2);
/*Antropologia*/
insert into cadeiras(nome, cursoID, ano, semestre) values('Fundamentos da Evolução e Genética', 3, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Introdução à Antropologia Básica', 3, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Primatologia', 3, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Teoria Social e Moderna', 3, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Teoria e História da Antropologia I', 3, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Antropologia da Religião', 3, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Dinâmica das Populações Humanas', 3, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Fundamentos de Estatística Aplicada', 3, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Paleoantropologia', 3, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Teoria e História da Antropologia II', 3, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Antropologia Visual', 3, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Antropologia do Corpo', 3, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Biologia do do Comportamento', 3, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Cultura Material e Museologia', 3, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Introdução à Antropologia Médica', 3, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Leituras Avançadas em Antropologia', 3, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Antropologia Evolutiva', 3, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Antropologia da Performance', 3, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Cultura e Cognição', 3, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Ecologia Humana e Adaptação', 3, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Espaço, Cultura e Globalização', 3, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Etnografia e Trabalho de Campo', 3, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Genética Evolutiva das Populações Humanas', 3, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Antropologia e Arquitectura', 3, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Evolução Social', 3, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Introdução à Antropologia Forense', 3, 3, 2);
/*Engenharia e Gestão Industrial*/
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática I', 4, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Desenho Técnico', 4, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física Geral', 4, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Introdução aos Materiais', 4, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Álgebra Linear e Geometria Analítica', 4, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática II', 4, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Eletromagnetismo e Eletricidade', 4, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Introdução à Gestão', 4, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Materiais para Engenharia', 4, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Programação', 4, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática III', 4, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecânica dos Sólidos e Estruturas', 4, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Processos de Fabrico I', 4, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Termodinâmica Aplicada', 4, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Tratamento Estatístico de Dados', 4, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Automação e Controlo Industrial', 4, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Economia de Empresa', 4, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Estatística Aplicada à Engenharia', 4, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Métodos Numéricos e Computacionais', 4, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Processos de Fabrico II', 4, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Elementos de Máquinas', 4, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Fundamentos de Investigação Operacional', 4, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Gestão Financeira', 4, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Gestão de Operações', 4, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecânica de Fluidos', 4, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Eletrotecnia e Máquinas Elétricas', 4, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Gestão da Qualidade', 4, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Logística', 4, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projeto e Produção Assistidos por Computador', 4, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Trasmissão de Calor', 4, 3, 2);
/*Matemática*/
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Infinitesimal I', 5, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Geometria', 5, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Teoria dos Números', 5, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Álgebra Linear e Geometria Analítica I', 5, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Infinitesimal II', 5, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Matemática Discreta', 5, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Métodos de Programação I', 5, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Álgebra Linear e Geometria Analítica II', 5, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Infinitesimal III', 5, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Equações Diferenciais e Modelação', 5, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Grupos e Simetrias', 5, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Métodos de Programação', 5, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Infinitesimal IV', 5, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Corpos e Equações Algébricas', 5, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Curvas e Superfícies', 5, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Probablidades', 5, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física', 5, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física Moderna', 5, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecânica Quântica', 5, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Estatística', 5, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Matemática Numérica I', 5, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Bases de Dados', 5, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Lógica', 5, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Topologia E Análise Linear', 5, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Complexa', 5, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Estatistica Computacional', 5, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Matemática Numérica II', 5, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Seminário Matemático', 5, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecânica Celeste', 5, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Programação Linear', 5, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Programação Orientada para os Objectos', 5, 3, 2);
/*Arquitetura*/
insert into cadeiras(nome, cursoID, ano, semestre) values('Construção I', 6, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Introdução à Arquitetura e à Cidade I', 6, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Construção II', 6, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Introdução à Arquitetura e à Cidade II', 6, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Desenho I', 6, 1, 3);
insert into cadeiras(nome, cursoID, ano, semestre) values('Geometria', 6, 1, 3);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projeto I', 6, 1, 3);
insert into cadeiras(nome, cursoID, ano, semestre) values('Construção III', 6, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Desenho II', 6, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('História da Arquitetura I', 6, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Teoria da Arquitetura I', 6, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Arquitetura e Projeto Digital I', 6, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Construção IV', 6, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('História da Arquitetura II', 6, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Teoria da Arquitetura II', 6, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projeto II', 6, 2, 3);
insert into cadeiras(nome, cursoID, ano, semestre) values('Arquitetura e Projeto Digital II', 6, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Construção V', 6, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('História da Arquitetura III', 6, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Teoria da Arquitetura III', 6, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Construção VI', 6, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Desenho III', 6, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('História da Arquitetura IV', 6, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Urbanismo', 6, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projeto III', 6, 3, 3);
insert into cadeiras(nome, cursoID, ano, semestre) values('História da Arquitetura Portuguesa I', 6, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Urbanística', 6, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Arqueologia da Paisagem, Cidade e Território', 6, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Concepção Construtiva e Ambiental', 6, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Do projeto à obra - do licenciamento camarário à preparação da execução da obra', 6, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Fotografia e Composição', 6, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Outras paisagens: habitação e espaço urbano hoje', 6, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas estruturais em edíficios', 6, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Suportes Físicos para Arquitetura e Urbanismo', 6, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('História da Arquitetura Portuguesa II', 6, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Urbanização', 6, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Arquitetura Portuguesa do Século XX', 6, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Estratégias de Reabilitação funcional de edíficios', 6, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Geografia Urbana', 6, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Gestão e Financiamento da Reabilitação', 6, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('História e Estética do Cinema', 6, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Investigação em Arquitetura', 6, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Políticas e Direito da Reabilitação', 6, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Teorias e Práticas de Reconstrução', 6, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Ambiente e Organização do Espaço', 6, 4, 4);
insert into cadeiras(nome, cursoID, ano, semestre) values('Antropologia, Cultura e Arquitetura', 6, 4, 4);
insert into cadeiras(nome, cursoID, ano, semestre) values('Arquiteturas Virtuais', 6, 4, 4);
insert into cadeiras(nome, cursoID, ano, semestre) values('Arquitetónicas da Forma', 6, 4, 4);
insert into cadeiras(nome, cursoID, ano, semestre) values('Conceitos e Práticas da Arte Contemporânea', 6, 4, 4);
insert into cadeiras(nome, cursoID, ano, semestre) values('Construção do Edificado - Condições para a Prática Projetual Construtiva II', 6, 4, 4);
insert into cadeiras(nome, cursoID, ano, semestre) values('Construção do Edificado - Condições para a Prática Projetual Construtiva I', 6, 4, 4);
insert into cadeiras(nome, cursoID, ano, semestre) values('Construção e Tecnologia', 6, 4, 4);
insert into cadeiras(nome, cursoID, ano, semestre) values('Expressão Plástica e Multimédia', 6, 4, 4);
insert into cadeiras(nome, cursoID, ano, semestre) values('Gestão de Energia em Edifícios', 6, 4, 4);
insert into cadeiras(nome, cursoID, ano, semestre) values('Instalações Técnicas em Edifícios', 6, 4, 4);
insert into cadeiras(nome, cursoID, ano, semestre) values('Intervenção no Património Cultural Edificado', 6, 4, 4);
insert into cadeiras(nome, cursoID, ano, semestre) values('Materiais Geológicos e Arquitetura', 6, 4, 4);
insert into cadeiras(nome, cursoID, ano, semestre) values('Organização do Projeto e Prática Profissional', 6, 4, 4);
insert into cadeiras(nome, cursoID, ano, semestre) values('Políticas e Direito de Reabilitação', 6, 4, 4);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projeto Moderno e Arquitetura', 6, 4, 4);
insert into cadeiras(nome, cursoID, ano, semestre) values('Urbanismo Arquitetura e Turismo', 6, 4, 4);
insert into cadeiras(nome, cursoID, ano, semestre) values('Seminário de Investigação', 6, 5, 1);
/*Engenharia Civil*/
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática I', 7, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física Geral I', 7, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Informática', 7, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Introdução à Engenharia Civil', 7, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química Geral', 7, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Álgebra Linear e Geometria Analítica', 7, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática II', 7, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física Geral', 7, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecânica I', 7, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Métodos Estatísticos', 7, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Topografia', 7, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática III', 7, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Competência Transversal I', 7, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Desenho Técnico', 7, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecânica II', 7, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecânica dos Meios Contínuos', 7, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Métodos Numéricos', 7, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Geologia da Engenharia', 7, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Hidráulica Geral I', 7, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Materiais de Construção', 7, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Resistência dos Materiais I', 7, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas de Engenharia', 7, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Hidráulica Geral II', 7, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecânica dos Solos I', 7, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Planeamento Regional e Urbano', 7, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Cartografia e Sistemas de Informação Geográfica', 7, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física das Construções', 7, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Geodesia', 7, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Geologia Estrutural', 7, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecânica das Rochas', 7, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Resistência dos Materiais II', 7, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Betão Armado I', 7, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Cadastro', 7, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Cartografia Geológica', 7, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Fotogrametria', 7, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Hidrologia e Recursos Hídricos', 7, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecânica dos Solos II', 7, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mineralogia e Petrologia', 7, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Prospecção Geofísica', 7, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Teoria das Estruturas I', 7, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Topografia Aplicada', 7, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Vias de Comunicação I', 7, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Betão Armado II', 7, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Saneamento Básico', 7, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Tecnologia das Construções', 7, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Teoria das Estruturas II', 7, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Vias de Comunicação II', 7, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Direcção, Gestão e Fiscalização de Obras', 7, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Estruturas Metálicas', 7, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Fundações', 7, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Gestão de Empreendimentos', 7, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Impactes Ambientais', 7, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projecto Urbano', 7, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Competência Transversal II', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Competência Transversal III', 7, 5, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Dissertação em Construções', 7, 5, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Acústica Aplicada', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Comportamento Térmico e Energético de Edifícios', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Construção Sustentável', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Instalações e Sistemas Técnicos em Edifícios', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Reabilitação Não-Estrutural', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Segurança e Processos Gerais de Construção', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sustentabilidade do Ambiente Construído', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Dissertação em Estruturas', 7, 5, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Conceção e Dimensionamento de Estruturas', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Conservação e Reabilitação de Estruturas', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Estruturas de Betão', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Estruturas de Madeira e Alvenaria', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projecto Assistido por Computador', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Dissertação em Geotecnia', 7, 5, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Engenharia Sísmica Geotécnica', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecânica dos Solos do Estado Crítico', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Obras de Escavação e Contenção', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Obras de Terra', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Dissertação em Hidráulica, Recursos Hídricos e Ambiente', 7, 5, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Aproveitamentos Energéticos', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Engenharia Fluvial e Costeira', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Gestão Integrada de Recursos Hídricos', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Instalações e Obras Hidráulicas', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projecto Assistido por Computador em Hidráulica Urbana', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projecto e Exploração de ETAR', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Dissertação em Mecânica Estrutural', 7, 5, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Não Linear de Estruturas', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Dinâmica e Dimensionamento Sísmico', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Estruturas Metálicas II', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Pontes', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projecto de Estrutura e Fundações', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Dissertação em Urbanismo, Transportes e Vias de Comunicação', 7, 5, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Engenharia de Infraestruturas de Transporte', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Engenharia de Tráfego', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Planeamento de Equipamentos Coletivos', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Planeamento de Transportes', 7, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Planeamento e Gestão Urbanística Municipal', 7, 5, 1);
/*Engenharia Do Ambiente*/
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática I', 8, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Desenho Técnico', 8, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física Geral I', 8, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Informática', 8, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Introdução à Engenharia do Ambiente', 8, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química Geral', 8, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática II', 8, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Cartografia e Sistemas de Informação Geográfica', 8, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Física Geral II', 8, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Geologia Geral', 8, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Álgebra Linear e Geometria Analítica', 8, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática III', 8, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Biologia', 8, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Métodos Numéricos', 8, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química Orgânica', 8, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Química-Física', 8, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Microbiologia', 8, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Métodos Estatísticos', 8, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Métodos Instrumentais de Análise', 8, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas de Engenharia', 8, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Termodinâmica', 8, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Ecologia Geral', 8, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecânica dos Fluidos', 8, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecânica dos Solos', 8, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mudanças Globais e Climatologia', 8, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Planeamento Regional e Urbano', 8, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Acústica Ambiental', 8, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise de Riscos', 8, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Ecologia Aplicada', 8, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Fenómenos de Transferência', 8, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Hidrologia e Recursos Hídricos', 8, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Competência Transversal I', 8, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Economia Ambiental', 8, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Efluentes Gasosos e Qualidade do Ar', 8, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Gestão Ambiental', 8, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas de Abastecimento e Drenagem de Água', 8, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Tratamentos Físico-Químicos', 8, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Geotecnia Ambiental', 8, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Gestão e Tratamento de Resíduos', 8, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Impactes Ambientais', 8, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas Energéticos', 8, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Tratamentos Biológicos', 8, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Dissertação de Mestrado em Tecnologia e Gestão do Ambiente', 8, 5, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Competência Transversal II', 8, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Ecologia Industrial', 8, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Energética do Meio Ambiente', 8, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Gestão de Energia', 8, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Higiene e Segurança', 8, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Materiais e Reciclagem', 8, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Competência Transversal III', 8, 5, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Dissertação (Território e Gestão do Ambiente)', 8, 5, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Gestão da Água', 8, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Gestão de Energia em Edifícios', 8, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Políticas e Desenvolvimento Sustentável', 8, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas Fluviais Costeiros', 8, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Transportes e Ambiente', 8, 5, 1);
/*Engenharia Eletrotécnica e de Computadores*/
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática I', 9, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Laboratório de Sistemas Digitais', 9, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Programação de Computadores', 9, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Álgebra Linear e Geometria Analítica', 9, 1, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática II', 9, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Competências Transversais para a Engenharia', 9, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Laboratório de Circuitos e Simulação', 9, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecânica e Ondas', 9, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas de Microprocessadores', 9, 1, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Análise Matemática III', 9, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Circuitos Eléctricos', 9, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Materiais Elétricos e Semicondutores', 9, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projeto I', 9, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sinais e Sistemas', 9, 2, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Electromagnetismo', 9, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Electrónica I', 9, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Estruturas de Dados e Algoritmos', 9, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Probabilidades e Estatística', 9, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Processamento de Sinal', 9, 2, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Bases de Dados', 9, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Conversão de Energia Elétrica', 9, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Electrónica II', 9, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Ondas e Propagação', 9, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas de Controlo', 9, 3, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projeto II', 9, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Técnicas de Planeamento e Gestão', 9, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Automação Industrial', 9, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Instrumentação e Medidas', 9, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Introdução aos Sistemas de Energia Eléctrica', 9, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Introdução às Comunicações', 9, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Redes de Computadores', 9, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas Embebidos', 9, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas Operativos', 9, 3, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Controlo Digital', 9, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Robótica', 9, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sensores Inteligentes', 9, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas de Tempo Real', 9, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mecatrónica', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projecto de Controlo Digital', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas Robóticos Autónomos', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Visão por Computador', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Compatibilidade Electromagnética', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Complementos de Investigação Operacional', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Elementos Finitos Aplicados à Engenharia Eletrotécnica', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Fabricação Digital e Sistemas Micro-Electrónico-Mecânicos', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Gestão Inteligente de Energia em Edifícios', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Microondas', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Processamento Avançado de Vídeo', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Seleção e Manutenção de Motores Elétricos', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas Rádio Definidos por Software', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Controlo Difuso e Aprendizagem', 9, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Empreendedorismo, Inovação e Transferência de Tecnologia', 9, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projeto de Dissertação', 9, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Dissertação', 9, 5, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Aplicações de Accionamentos Eléctricos', 9, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Co-Projecto de Hardware e Software', 9, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Comunicações nas Redes Elétricas Inteligentes', 9, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Controlo Não Destrutivo', 9, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Fundamentos de Investigação Operacional', 9, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Mercados e Qualidade de Energia', 9, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Redes de Transporte e Acesso de Próxima Geração', 9, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Redes Ópticas', 9, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Robótica Médica', 9, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas de Controlo de Potência', 9, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas e Robôs Interativos', 9, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Visão Robótica', 9, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Electrónica de Potência', 9, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Redes Elétricas Inteligentes', 9, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Arquitectura de Computadores', 9, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Engenharia de Software', 9, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Processamento Digital de Sinal', 9, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Computação Gráfica e Realidade Aumentada', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Internet das Coisas', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projecto de Sistemas Digitais', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Comunicações Móveis', 9, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Computação Heterogénea de Alto Desempenho', 9, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Produção de Energia Elétrica', 9, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Projectos de Instalações Eléctricas', 9, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Regime Estacionário em Sistemas de Energia Elétrica', 9, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Transformadores e Máquinas Assíncronas', 9, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Acionamentos Elétricos', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Gestão de Energia Eléctrica', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Máquinas Síncronas', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Regime Transitório em Sistemas de Energia Elétrica', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Proteções e Fiabilidade em Sistemas de Energia Elétrica', 9, 5, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Antenas', 9, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Electrónica para Telecomunicações', 9, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Fundamentos de Sistemas de Comunicação', 9, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Teoria da Informação e da Codificação', 9, 4, 1);
insert into cadeiras(nome, cursoID, ano, semestre) values('Engenharia de Redes de Comunicação', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas de Comunicação Digital', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Sistemas de Comunicação Ópticos', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Transmissão de Informação Multimédia', 9, 4, 2);
insert into cadeiras(nome, cursoID, ano, semestre) values('Tecnologias de Redes de Comunicação', 9, 5, 1);
